# Adult Income Data Cleaning and EDA

In [1]:
# import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests

from pathlib import Path

In [2]:
# define project paths

PROJECT_DIR = Path("..")

DATA_DIR = PROJECT_DIR / "data"

REPORTS_DIR = PROJECT_DIR / "reports"

CHARTS_DIR = REPORTS_DIR / "charts"

TABLES_DIR = REPORTS_DIR / "summary_tables"

print("Data folder:", DATA_DIR)
print("Reports folder:", REPORTS_DIR)

Data folder: ..\data
Reports folder: ..\reports

In [3]:
# define dataset urls

adult_data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

adult_test_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test"

In [4]:
# define file paths

adult_data_path = DATA_DIR / "adult.data"

adult_test_path = DATA_DIR / "adult.test"

print(adult_data_path)
print(adult_test_path)

..\data\adult.data
..\data\adult.test

In [5]:
# download adult.data

response = requests.get(adult_data_url)

if response.status_code == 200:
    adult_data_path.write_bytes(response.content)
    print("adult.data downloaded successfully")
else:
    print("Failed to download adult.data")
    print("Status code:", response.status_code)

adult.data downloaded successfully

In [6]:
# download adult.test

response = requests.get(adult_test_url)

if response.status_code == 200:
    adult_test_path.write_bytes(response.content)
    print("adult.test downloaded successfully")
else:
    print("Failed to download adult.test")
    print("Status code:", response.status_code)

adult.test downloaded successfully

In [7]:
# verify downloaded files

print("adult.data exists:", adult_data_path.exists())
print("adult.test exists:", adult_test_path.exists())

adult.data exists: True
adult.test exists: True

In [8]:
# define column names

columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

print("Total Columns:", len(columns))
print(columns)

Total Columns: 15
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income']

In [9]:
# load adult.data

adult_data = pd.read_csv(
    adult_data_path,
    header=None,
    names=columns
)

adult_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [10]:
# load adult.test

adult_test = pd.read_csv(
    adult_test_path,
    header=None,
    names=columns,
    skiprows=1
)

adult_test.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [11]:
# check dataset shapes

print("adult.data shape :", adult_data.shape)
print("adult.test shape :", adult_test.shape)

adult.data shape : (32561, 15)
adult.test shape : (16281, 15)

In [12]:
# inspect raw datasets

print("adult.data info")
adult_data.info()

print("\nadult.test info")
adult_test.info()

adult.data info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

adult.test info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16281 entries, 0 to 16280
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             16281 non-null  int64
 1   workclass       16281 non-null  object
 2   fnlwgt          16281 non-null  int64
 3   education       16281 non-null  object
 4   education_num   16281 non-null  int64
 5   marital_status  16281 non-null  object
 6   occupation      16281 non-null  object
 7   relationship    16281 non-null  object
 8   race            16281 non-null  object
 9   sex             16281 non-null  object
 10  capital_gain    16281 non-null  int64
 11  capital_loss    16281 non-null  int64
 12  hours_per_week  16281 non-null  int64
 13  native_country  16281 non-null  object
 14  income          16281 non-null  object
dtypes: int64(6), object(9)
memory usage: 1.9+ MB

In [13]:
# display sample records

adult_data.sample(5, random_state=42)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
14160,27,Private,160178,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,Female,0,0,38,United-States,<=50K
27048,45,State-gov,50567,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
28868,29,Private,185908,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,55,United-States,>50K
5667,30,Private,190040,Bachelors,13,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
7827,29,Self-emp-not-inc,189346,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,2202,0,50,United-States,<=50K

In [14]:
# add source split

adult_data["source_split"] = "train"
adult_test["source_split"] = "test"

In [15]:
# combine train and test data

df = pd.concat(
    [adult_data, adult_test],
    ignore_index=True
)

print("Combined dataset shape:", df.shape)

Combined dataset shape: (48842, 16)

In [16]:
# inspect combined dataset

df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,source_split
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,train
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,train
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,train
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,train
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,train

In [17]:
# check last records

df.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,source_split
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.,test
48838,64,?,321403,HS-grad,9,Widowed,?,Other-relative,Black,Male,0,0,40,United-States,<=50K.,test
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.,test
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.,test
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.,test

In [18]:
# check dataset shape

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 48842
Columns: 16

In [19]:
# check source split

print(df["source_split"].value_counts())

source_split
train    32561
test     16281
Name: count, dtype: int64

In [20]:
# check source split percentage

print(
    df["source_split"].value_counts(normalize=True) * 100
)

source_split
train    66.665984
test     33.334016
Name: proportion, dtype: float64

In [21]:
# check column names

print(df.columns.tolist())

['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'source_split']

In [22]:
# save combined raw dataset

raw_combined_path = DATA_DIR / "adult_income_combined_raw.csv"

df.to_csv(raw_combined_path, index=False)

print("Combined raw dataset saved successfully.")

Combined raw dataset saved successfully.

In [23]:
# check categorical columns

categorical_columns = df.select_dtypes(include="object").columns

print(categorical_columns)

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income',
       'source_split'],
      dtype='object')

In [24]:
# remove leading and trailing whitespace

for column in categorical_columns:
    df[column] = df[column].str.strip()

In [25]:
# check question mark values

question_mark_counts = (df == "?").sum()

print(question_mark_counts)

age                  0
workclass         2799
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     857
income               0
source_split         0
dtype: int64

In [26]:
# check empty string values

empty_counts = (df == "").sum()

print(empty_counts)

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
source_split      0
dtype: int64

In [27]:
# convert question marks and empty strings to missing values

df = df.replace(["?", ""], np.nan)

In [28]:
# check missing values

missing_values = df.isnull().sum()

print(missing_values)

age                  0
workclass         2799
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     857
income               0
source_split         0
dtype: int64

In [29]:
# calculate missing value percentage

missing_percentage = (
    df.isnull().sum() / len(df) * 100
)

print(missing_percentage)

age               0.000000
workclass         5.730724
fnlwgt            0.000000
education         0.000000
education_num     0.000000
marital_status    0.000000
occupation        5.751198
relationship      0.000000
race              0.000000
sex               0.000000
capital_gain      0.000000
capital_loss      0.000000
hours_per_week    0.000000
native_country    1.754637
income            0.000000
source_split      0.000000
dtype: float64

In [30]:
# display missing value summary

missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().sum() / len(df) * 100
})

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
]

missing_summary

                missing_count  missing_percentage
workclass                2799            5.730724
occupation               2809            5.751198
native_country            857            1.754637

In [31]:
# define categorical columns with missing values

missing_categorical_columns = [
    "workclass",
    "occupation",
    "native_country"
]

In [32]:
# replace missing categorical values with Unknown

for column in missing_categorical_columns:
    df[column] = df[column].fillna("Unknown")

In [33]:
# verify categorical missing values

print(df[missing_categorical_columns].isnull().sum())

workclass         0
occupation        0
native_country    0
dtype: int64

In [34]:
# count Unknown values

for column in missing_categorical_columns:
    print(column, ":", (df[column] == "Unknown").sum())

workclass : 2799
occupation : 2809
native_country : 857

In [35]:
# check remaining missing values

print(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
source_split      0
dtype: int64

In [36]:
# define numeric columns

numeric_columns = [
    "age",
    "fnlwgt",
    "education_num",
    "capital_gain",
    "capital_loss",
    "hours_per_week"
]

print(numeric_columns)

['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

In [37]:
# convert numeric columns

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

In [38]:
# check numeric missing values

print(df[numeric_columns].isnull().sum())

age               0
fnlwgt            0
education_num     0
capital_gain      0
capital_loss      0
hours_per_week    0
dtype: int64

In [39]:
# inspect numeric columns

df[numeric_columns].describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [40]:
# check impossible numeric values

print("Age below 0:", (df["age"] < 0).sum())
print("Education number below 0:", (df["education_num"] < 0).sum())
print("Hours below 0:", (df["hours_per_week"] < 0).sum())
print("Capital gain below 0:", (df["capital_gain"] < 0).sum())
print("Capital loss below 0:", (df["capital_loss"] < 0).sum())

Age below 0: 0
Education number below 0: 0
Hours below 0: 0
Capital gain below 0: 0
Capital loss below 0: 0

In [41]:
# check invalid core numeric values

print("Missing age:", df["age"].isnull().sum())
print("Missing education_num:", df["education_num"].isnull().sum())
print("Missing hours_per_week:", df["hours_per_week"].isnull().sum())

print("Age below 1:", (df["age"] < 1).sum())
print("Hours per week below 1:", (df["hours_per_week"] < 1).sum())

Missing age: 0
Missing education_num: 0
Missing hours_per_week: 0
Age below 1: 0
Hours per week below 1: 0

In [42]:
# check numeric data types

print(df[numeric_columns].dtypes)

age               int64
fnlwgt            int64
education_num     int64
capital_gain      int64
capital_loss      int64
hours_per_week    int64
dtype: object

In [43]:
# remove rows with invalid core numeric values

before_numeric_cleaning = len(df)

valid_numeric_mask = (
    df["age"].notna()
    & (df["age"] > 0)
    & df["education_num"].notna()
    & (df["education_num"] > 0)
    & df["hours_per_week"].notna()
    & (df["hours_per_week"] > 0)
)

df = df[valid_numeric_mask].copy()

after_numeric_cleaning = len(df)

print("Rows before numeric cleaning:", before_numeric_cleaning)
print("Rows after numeric cleaning:", after_numeric_cleaning)
print("Rows removed:", before_numeric_cleaning - after_numeric_cleaning)

Rows before numeric cleaning: 48842
Rows after numeric cleaning: 48842
Rows removed: 0

In [44]:
# check duplicate rows

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 29

In [45]:
# calculate duplicate percentage

duplicate_percentage = (
    duplicate_count / len(df) * 100
)

print("Duplicate percentage:", duplicate_percentage)

Duplicate percentage: 0.05937512796363785

In [46]:
df.drop_duplicates()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,source_split
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,train
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,train
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,train
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,train
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.,test
48838,64,Unknown,321403,HS-grad,9,Widowed,Unknown,Other-relative,Black,Male,0,0,40,United-States,<=50K.,test
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.,test
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.,test
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.,test

In [47]:
# check income labels

print(df["income"].value_counts())

income
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [48]:
# remove trailing period from income labels

df["income"] = df["income"].str.rstrip(".")

In [49]:
# verify income labels

print(df["income"].value_counts())

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [50]:
# check unique income labels

print(df["income"].unique())

['<=50K' '>50K']

In [51]:
# validate income labels

valid_income_labels = ["<=50K", ">50K"]

invalid_income_labels = ~df["income"].isin(valid_income_labels)

print("Invalid income labels:", invalid_income_labels.sum())

Invalid income labels: 0

In [52]:
# create high income flag

df["high_income"] = (
    df["income"] == ">50K"
).astype(int)

In [53]:
# check high income flag

print(df["high_income"].value_counts())

high_income
0    37155
1    11687
Name: count, dtype: int64

In [54]:
# compare income and high income

print(
    pd.crosstab(
        df["income"],
        df["high_income"]
    )
)

high_income      0      1
income
<=50K        37155      0
>50K             0  11687

In [55]:
# calculate high income rate

high_income_rate = df["high_income"].mean() * 100

print("Above $50K rate:", high_income_rate)

Above $50K rate: 23.928176569346054

In [56]:
# create age groups

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 35, 45, 55, 65, np.inf],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "66+"
    ]
)

In [57]:
# check age groups

print(df["age_group"].value_counts().sort_index())

age_group
18-25     9627
26-35    12719
36-45    11952
46-55     8296
56-65     4445
66+       1803
Name: count, dtype: int64

In [58]:
# create weekly working hour groups

df["hours_band"] = pd.cut(
    df["hours_per_week"],
    bins=[0, 20, 40, 60, np.inf],
    labels=[
        "<=20",
        "21-40",
        "41-60",
        "61+"
    ]
)

In [59]:
# check weekly hour groups

print(df["hours_band"].value_counts().sort_index())

hours_band
<=20      4453
21-40    30037
41-60    12676
61+       1676
Name: count, dtype: int64

In [60]:
# create net capital gain or loss

df["net_capital"] = (
    df["capital_gain"] - df["capital_loss"]
)

In [61]:
# check newly created features

print(
    df[
        [
            "age_group",
            "hours_band",
            "net_capital",
            "high_income"
        ]
    ].head()
)

  age_group hours_band  net_capital  high_income
0     36-45      21-40         2174            0
1     46-55       <=20            0            0
2     36-45      21-40            0            0
3     46-55      21-40            0            0
4     26-35      21-40            0            0

In [62]:
# check final dataset shape

print("Final rows:", df.shape[0])
print("Final columns:", df.shape[1])

Final rows: 48842
Final columns: 20

In [63]:
# final missing value check

missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().sum() / len(df) * 100
})

missing_summary[missing_summary["missing_count"] > 0]

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

In [64]:
# check final data types

print(df.dtypes)

age                  int64
workclass           object
fnlwgt               int64
education           object
education_num        int64
marital_status      object
occupation          object
relationship        object
race                object
sex                 object
capital_gain         int64
capital_loss         int64
hours_per_week       int64
native_country      object
income              object
source_split        object
high_income          int64
age_group         category
hours_band        category
net_capital          int64
dtype: object

In [65]:
# check final columns

print(df.columns.tolist())

['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'source_split', 'high_income', 'age_group', 'hours_band', 'net_capital']

In [66]:
# validate income values

print("Unique income values:")
print(df["income"].unique())

print("\nHigh income values:")
print(df["high_income"].unique())

Unique income values:
['<=50K' '>50K']

High income values:
[0 1]

In [67]:
# validate high income mapping

income_check = pd.crosstab(
    df["income"],
    df["high_income"]
)

income_check

high_income      0      1
income
<=50K        37155      0
>50K             0  11687

In [68]:
# create cleaning summary

cleaning_summary = pd.DataFrame({
    "check": [
        "Initial records",
        "Final records",
        "Initial columns",
        "Final columns",
        "Duplicate rows",
        "Remaining missing values"
    ],
    "value": [
        48842,
        len(df),
        15,
        len(df.columns),
        duplicate_count,
        df.isnull().sum().sum()
    ]
})

cleaning_summary

                      check  value
0           Initial records  48842
1             Final records  48842
2           Initial columns     15
3             Final columns     20
4            Duplicate rows     29
5  Remaining missing values      0

In [69]:
# save cleaning log

cleaning_log_path = TABLES_DIR / "cleaning_log.csv"

cleaning_summary.to_csv(
    cleaning_log_path,
    index=False
)

print("Cleaning log saved successfully.")

Cleaning log saved successfully.

In [70]:
# save cleaned dataset

cleaned_data_path = DATA_DIR / "adult_income_cleaned.csv"

df.to_csv(
    cleaned_data_path,
    index=False
)

print("Cleaned dataset saved successfully.")
print("File:", cleaned_data_path)

Cleaned dataset saved successfully.
File: ..\data\adult_income_cleaned.csv

In [71]:
# verify cleaned dataset

cleaned_df = pd.read_csv(cleaned_data_path)

print("Saved dataset shape:", cleaned_df.shape)

Saved dataset shape: (48842, 20)

In [72]:
# inspect cleaned dataset

cleaned_df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,source_split,high_income,age_group,hours_band,net_capital
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,train,0,36-45,21-40,2174
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,train,0,46-55,<=20,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,train,0,36-45,21-40,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,train,0,46-55,21-40,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,train,0,26-35,21-40,0